### ISSUE TITLE
同步失败

### ISSUE THREAD

**Issue by TankardYegga** [sethyuan/logseq-plugin-weread-sync#1]
logseq报错“[Main Exception]EBADF: bad file descriptor, writeError: EBADF: bad file descriptor, write”，而浏览器报错“同步失败”，这是咋回事呢？

**Comment by sethyuan** [comment]
HTTP APIs Server应该是没启动起来，好像是个已知问题，你查一查Logseq的issues呢。

**Comment by TankardYegga** [comment]
https://github.com/logseq/logseq/pull/8631 这个里面说已经解决了这个bug，server是正常开启的，只是有这个日志打印得不对。我现在是最新版本的logseq，并且HTTP API server能正常访问页面。

**Comment by TankardYegga** [comment]
![image](https://user-images.githubusercontent.com/48079583/220820524-07624ea5-a3dc-4c68-b5ac-96caf5323934.png)
但是还是无法使用该插件，这是chrome extension里面的errors，我配置的token是正确的，并没有错误。所以，是不是这校验的代码存在问题呢？

**Comment by TankardYegga** [comment]
> ![image](https://user-images.githubusercontent.com/48079583/220820524-07624ea5-a3dc-4c68-b5ac-96caf5323934.png) 但是还是无法使用该插件，这是chrome extension里面的errors，我配置的token是正确的，并没有错误。所以，是不是这校验的代码存在问题呢？

![image](https://user-images.githubusercontent.com/48079583/220822780-0a6b634c-5f25-4f18-bf6e-55aca2b1e21b.png)
打开匀速自动运行对这些网站的访问权限后，就没有这个错误了。但是显示“同步失败”，报了404的错误：
![image](https://user-images.githubusercontent.com/48079583/220822942-214ecb8e-d47e-470c-96bf-a100356fb791.png)

**Comment by TankardYegga** [comment]
![image](https://user-images.githubusercontent.com/48079583/220823540-9151466c-b253-4b29-9526-8ee63e016cd6.png)

这是我在chrome console看到的具体报错信息

**Comment by sethyuan** [comment]
嗯，之前看起来是权限的问题，最后这个看起来可能是偶发的。你试试重新加载插件和重启浏览器看看呢。

**Comment by sethyuan** [comment]
我测试下来貌似只要数据太多微信读书就是会报这个错，但是多执行几次就可以了。

**Comment by TankardYegga** [comment]
> 我测试下来貌似只要数据太多微信读书就是会报这个错，但是多执行几次就可以了。

![image](https://user-images.githubusercontent.com/48079583/220837022-f340e947-5739-4db9-823b-7ddb4a7e8276.png)

我都实验了十几次了，根本不行的，应该还是程序有bug。不管怎么样，写写了，近期我还是不用这个了，问题太多了

**Comment by sethyuan** [comment]
嗯，这个问题确实很奇怪，我这儿也重现不了。如果能重现的话我再关注下。

**Comment by sethyuan** [comment]
@TankardYegga 你下次再出现的时候能否在devtools里切换到network的tab下，找到出错的那个请求，看看它具体报的什么错。我这儿重现不了没法排查。

**Comment by sethyuan** [comment]
Chrome插件我更新了个0.3.0，将书籍获取的逻辑改成分批次的了，这样会慢一些，但说不定可以解决500的问题。

**Comment by TankardYegga** [comment]
> @TankardYegga 你下次再出现的时候能否在devtools里切换到network的tab下，找到出错的那个请求，看看它具体报的什么错。我这儿重现不了没法排查。

我换上你的3.0插件了，Network的截图如下：

![image](https://user-images.githubusercontent.com/48079583/221075430-ea5a2234-a473-4d51-a23e-ac8644dda81e.png)

Console的截图如下：

![image](https://user-images.githubusercontent.com/48079583/221075507-671b56e5-e2bc-4e04-82a1-9a476200d980.png)

看上去是已经成功获取数据了，但是不明白为啥还会弹出“同步失败”的字样

**Comment by TankardYegga** [comment]
我的pages数量并没有增加，也无法查询到任何数据：
![image](https://user-images.githubusercontent.com/48079583/221077724-74c5c97a-2c5a-4be4-802f-276dc26a21fd.png)

![image](https://user-images.githubusercontent.com/48079583/221077744-d0ffd8ee-00b3-48d7-a559-b0abdf62cbff.png)

**Comment by sethyuan** [comment]
截图里的错与本插件无关。提示同步失败后你右击它，点inspect打开调试窗口看下是什么原因，或者在插件管理那儿看看是什么错误。

**Comment by TankardYegga** [comment]
> 截图里的错与本插件无关。提示同步失败后你右击它，点inspect打开调试窗口看下是什么原因，或者在插件管理那儿看看是什么错误。

谢谢你~，我不太懂前端知识，描述得不够清晰。这是插件那块的错误：
![image](https://user-images.githubusercontent.com/48079583/221105128-6fcef198-c78f-4553-86e5-a5b2769b58af.png)

**Comment by sethyuan** [comment]
感觉是脚本注入没成功，你页面的URL是什么？插件权限都给了吗？

**Comment by TankardYegga** [comment]
页面的URL是https://weread.qq.com/，插件权限设置了，HTTP APIS SERVER也都开了，插件里面的token也都配置了。之前你说的无关的那个错误是我第一次打开微信读书网页时有的，确实与你的插件无关；再点击一下，插件就开始工作了，控制台没有报错，网络部分也是正常读取数据，但是再过一会就报错了。这时候我打开插件的errors就是你刚才那个页面了，然后我也打开了插件里的inspect popup页面，得到了下面的错误截图，我并不明白为啥插件的erros和这个popup inspect显示的错误并不一致：
![image](https://user-images.githubusercontent.com/48079583/221108088-7a7f2205-dc6a-4be1-b05c-cf5611d73071.png)

是不是还是因为我微信读书里的书太多的原因吗？

非常感谢！

**Comment by sethyuan** [comment]
413 是说数据太大了，是HTTP APIs Server的限制，我联系下Logseq团队看能否把限制放开点儿。不行的话我得花时间看看怎么调整代码，分批次往Logseq导入。

**Comment by TankardYegga** [comment]
> 413 是说数据太大了，是HTTP APIs Server的限制，我联系下Logseq团队看能否把限制放开点儿。不行的话我得花时间看看怎么调整代码，分批次往Logseq导入。

嗯嗯，分批次更好，因为还有很多比我的书架多的多的人，logseq也不能一直放开限制。

**Comment by sethyuan** [comment]
@TankardYegga 我实现了分批导入，浏览器插件要用0.4.0+的，Logseq端插件用0.2.0+。

**Comment by TankardYegga** [comment]
> @TankardYegga 我实现了分批导入，浏览器插件要用0.4.0+的，Logseq端插件用0.2.0+。

试过了，但是还是“同步失败”，浏览器和logseq安装的都是最新版本的插件。报的错误是：

![image](https://user-images.githubusercontent.com/48079583/222339111-bbf38eba-c4f1-48a7-a229-edd85c23fee4.png)

![image](https://user-images.githubusercontent.com/48079583/222339167-1c3d9cd7-2a80-47be-bcf2-218c3d24a451.png)

**Comment by sethyuan** [comment]
@TankardYegga 你看下Logseq这边的console，看报什么错没有。

**Comment by sethyuan** [comment]
要看下Logseq的console，你贴的这个是浏览器端的，这个之前已经给过了。
