### ISSUE TITLE
同步后提示同步失败

### ISSUE THREAD

**Issue by liamtao** [sethyuan/logseq-plugin-weread-sync#10]
现象：
第一次开启同步后，过了大概半分钟，提示同步失败。部分书籍的高亮已成功同步到logseq。
之后再次开启同步，大概3-4秒就提示同步失败。
![Xnip2023-05-21_07-03-37](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/9836684/a8d86b10-122f-4708-88cc-7e56f0dbf8d3)

猜测：
我的书架中有微信阅读官方书和一些自己上传的书，有的书名是重复的，不知道会不会对同步产生影响。

**Comment by sethyuan** [comment]
能否在同步失败后在Logseq这边打开console (ctrl+shift+i 或 cmd+shift+i) 看看具体是什么错。

**Comment by liamtao** [comment]
报错如下：
<img width="548" alt="image" src="https://github.com/sethyuan/logseq-plugin-weread-sync/assets/9836684/6d85ffee-1027-4f5e-bbfb-a9b94492b8ca">

**Comment by sethyuan** [comment]
看错误应该是某条划线的创建日期格式与正常的不太一样，导致转换日期出错。我调整了一下让它不出错，等导入完之后你再打开console看下出错的那个日期是什么样的，这回我把错误值也log下来了。新版本是0.3.3

**Comment by sethyuan** [comment]
BTW，书名不能完全一样哈，至少得有一个字符的差异，不然会导入到同一个Logseq页面中去，就冲突了。

**Comment by liamtao** [comment]
好的哈，谢谢！
