### ISSUE TITLE
显示成功但是报错，求解答

### ISSUE THREAD

**Issue by cwjgiegie** [sethyuan/logseq-plugin-weread-sync#11]
![图片](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/97a88b30-9921-4054-bedd-3ce9452d30a8)
![图片](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/f869eee1-6de5-4ae0-bd11-113c4e7cc0d1)

**Comment by sethyuan** [comment]
看截图你还没有创建Logseq库？

**Comment by cwjgiegie** [comment]
现在创建了，我是小白Github，平时我都是看csdn的，现在还是不行
![图片](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/cabbdb0b-111a-4e74-b41f-cd6a90055ca7)
![图片](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/9d6fe105-fee7-4584-b9f2-ec12b12b31ab)
麻烦大佬耐心指导一下我这个渣渣，谢谢辽

**Comment by sethyuan** [comment]
检查下Logseq中配置的API Server的token和地址与浏览器插件中设置的是否能对的上，要对的上才行。

**Comment by cwjgiegie** [comment]
自我感觉没问题，再指点一下
![图片](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/4e3c3168-ff17-4fa3-8312-611a08f1a87f)
![图片](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/fc2c0e3a-5841-454e-b14b-ead4437f91b4)
![图片](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/68e9f6dc-30fc-48d1-aa92-d3ccb94fc056)

**Comment by cwjgiegie** [comment]
还是不行，我又重新输入了一遍，授权令牌我也没换直接CV了您的那个

**Comment by sethyuan** [comment]
授权令牌也是两边都要匹配的，你是两边都配置了一样的吗？

**Comment by cwjgiegie** [comment]
![image](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/3d86b77c-c4ec-4c2d-b550-742a288a1098)
![image](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/f0f86ce0-494b-411c-97c4-cb23ea918ff7)
应该是的

**Comment by cwjgiegie** [comment]
![image](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/b6016fd0-f7b5-464c-a8d2-626f3d3a19b9)
我在知乎上看到这个，是不是因为没有做这一步啊，但是我在LogSeq也找不到这个页面啊

**Comment by sethyuan** [comment]
这个没关系。你检查下你Logseq端的API Server启动起来没？点击API的图表，再点里面的链接看能不能打开。

**Comment by cwjgiegie** [comment]
![image](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/9ae04c0b-5ed6-4643-9946-c2e3f989c193)
网页许可能allow的都开了
![image](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/787c654f-256e-4503-aeb3-9a052e189dbb)
![image](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/7ded0ed1-3d4b-4795-9f37-f70776e8b5b9)

**Comment by sethyuan** [comment]
我再问一句，你Logseq端安装插件了没？ 😂

**Comment by cwjgiegie** [comment]
我的错我的错，是手动安装插件吗是哪个，我真的不太懂
![image](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/008a631e-2b0c-4369-b863-96441be97e4b)

**Comment by sethyuan** [comment]
<img width="363" alt="image" src="https://github.com/sethyuan/logseq-plugin-weread-sync/assets/3410293/89b6721a-df27-4017-a5bb-d66143976bc4">

这个，通过插件市场安装。

**Comment by cwjgiegie** [comment]
![image](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/3ab102df-31a3-4e34-93e1-d0a3dec9650b)
就是这样等就好了吗？

**Comment by sethyuan** [comment]
出现蓝色的完成就是同步完了。Logseq中应该已经有数据了，你可以在“全部页面”中查看一下。

**Comment by cwjgiegie** [comment]
![image](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/55f8720b-8770-4469-9bfe-c90cfe9d082c)
是更新了，但是好像没有什么反应
![image](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/d8d081cf-319f-4058-a2ab-ac97aa818160)

**Comment by cwjgiegie** [comment]
请您再指导我一下哪里做得不对或者怎么做

**Comment by sethyuan** [comment]
插件会同步你书架里的书籍，看看你的书架里有没有书呢

**Comment by cwjgiegie** [comment]
![image](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/93698092/28d50ccc-3df3-419e-9984-d6a779a31614)
是的更新了，接下来做什么

**Comment by cwjgiegie** [comment]
已清除增量同步key

**Comment by sethyuan** [comment]
数据已经同步成功了。用就行了，我看你是Logseq新手，好像完全不懂Logseq咋用，你要不先看看它的文档。简单来说Logseq就是一个笔记软件。

**Comment by sethyuan** [comment]
这是微信读书的同步插件哈，只同步微信读书数据。
