### ISSUE TITLE
仅同步了划线，没有同步想法

### ISSUE THREAD

**Issue by plusczh** [sethyuan/logseq-plugin-weread-sync#12]
没有同步想法，搜索也无想法id

**Comment by sethyuan** [comment]
同步结束后出现的“完成”是蓝色还是红色的呢？如果是红色的，能否清除下增量key，如下图，再次同步出错后在Logseq中打开console（ctrl+shift+i 或 cmd+shift+i），将里面红色的出错信息截图贴上来看看。

<img width="460" alt="image" src="https://github.com/sethyuan/logseq-plugin-weread-sync/assets/3410293/c79eab19-781f-4dce-8f71-02244c08794a">

我这边用是正常的，想法是可以同步的。想法同步过来后是这个样子的：

<img width="737" alt="image" src="https://github.com/sethyuan/logseq-plugin-weread-sync/assets/3410293/a85f5d6a-54ac-4af7-82ad-4cf96ced332d">

**Comment by plusczh** [comment]
> 同步结束后出现的“完成”是蓝色还是红色的呢？如果是红色的，能否清除下增量key，如下图，再次同步出错后在Logseq中打开console（ctrl+shift+i 或 cmd+shift+i），将里面红色的出错信息截图贴上来看看。
> 
> <img alt="image" width="459" src="https://user-images.githubusercontent.com/3410293/253803521-945d92ee-a0c6-4688-bffe-1e29708e2ba6.png">
> 我这边用是正常的，想法是可以同步的。想法同步过来后是这个样子的：
> 
> <img alt="image" width="737" src="https://user-images.githubusercontent.com/3410293/253803433-a85f5d6a-54ac-4af7-82ad-4cf96ced332d.png">

谢谢，已经解决了。同步时间较长，中途再点开浏览器会断掉，另外同步规则好像是所有划线同步完才开始同步想法，我看文件数量没有变化以为同步完了。
