### ISSUE TITLE
同步笔记问题

### ISSUE THREAD

**Issue by Morganwan90** [sethyuan/logseq-plugin-weread-sync#13]
非常喜欢您制作的这个插件，在使用过程中遇到一些困惑，特来请教：

1. OB上的读书笔记插件同步的是“我”-“笔记”中的笔记内容，本插件的同步内容是书架上的笔记，这个我理解。我的情况是存在一些我以前读过的书，我把他移除了书架，所以造成没有同步到。 
为了适配此插件，我将书籍重新移回了书架，此时我在手机上点击“查看笔记”也可以看到我之前的划线。但是我点击插件同步后，仅同步了书籍内容，在移回书架前的笔记没有导入进来，移回书架后新创建的可以顺利导入。原来那些笔记划线，尽管在手机上可以看得到，但是没有同步过来，这个是否可以优化？

2. 手机的微信读书中，微信读书的书架分类成一个个文件夹叫分组，然后还有单独一个功能叫书单，可以加入书籍。
我设置了一个书单，书单名字为Unread，在chrome插件中设置了名称，仍然同步过来。
在书架中设置了一个分组，分组名为UnRead，成功没有同步。
所以应该是在书架中设置的那个分组才是扩展中屏蔽的“书单”，这里有点歧义...建议修改。

<img width="750" alt="2023-07-16_22-05-24" src="https://github.com/sethyuan/logseq-plugin-weread-sync/assets/61633409/feefe27a-ed5d-4541-8084-2011889f908b">

3. 元数据中很多都加上了[[*]]，我理解肯定有用户希望这样，但是可否加一个选择，让用户自行决定哪些需要创建页面，就我个人我可能只希望仅希望部分数据创建页面。

<img width="1121" alt="2023-07-17_02-42-47" src="https://github.com/sethyuan/logseq-plugin-weread-sync/assets/61633409/a20eedd6-b987-4575-895d-6c98735c3911">

再次谢谢作者的插件！

**Comment by sethyuan** [comment]
你的问题较多，我分别回答一下：

1. 可以尝试在Chrome插件设置中清除增量key，然后再同步一下，这样就会是一个全量同步了。
  <img width="459" alt="image" src="https://github.com/sethyuan/logseq-plugin-weread-sync/assets/3410293/f7f3d537-4d1e-4baf-8fd6-415876b8d35d">

2. 插件用的应该就是书单，不是书架中的分组，请再核对一下。

3. Logseq中的page就是tag，tag就是page，你把这些括号看成是插件给数据打的标签就可以了。打标签的话并不会创建物理页面，只有当你点击去写内容的时候才会真正创建页面。这些标签是方便以后检索用的，如果让用户自行设定的话就太复杂了，因为元数据太多了，而且也没有必要，就像我刚才说的，这些只是一些标签数据。

**Comment by Morganwan90** [comment]
可以了已成功。
看来确实是我弄错了，可能是延迟造成了。
现在已经可以正常使用，感谢！
