### ISSUE TITLE
Add English Readme

### ISSUE THREAD

**Issue by ard0gg** [sethyuan/logseq-plugin-weread-sync#14]
I noticed some of your other plugins have an English README option. Would be nice to have one included here as well.

**Comment by ard0gg** [comment]
That makes complete sense. Even just adding that note in the README would be sufficient, I think. I just happened to be browsing plugins/repos and came across this one not knowing anything about WeRead.

**Comment by sethyuan** [comment]
Good suggestion, I'll add an English README.

**Comment by sethyuan** [comment]
Done
