### ISSUE TITLE
初始同步一直在“获取数据”的问题

### ISSUE THREAD

**Issue by yanyang1025** [sethyuan/logseq-plugin-weread-sync#17]
开发者您好，想问一下按照instruction配置好以后，点击chrome插件第一次同步的时候一直仅显示“获取数据……”，过几秒之后就会消失了，然后什么都没有发生。这种情况应该怎么办呢？谢谢

**Comment by sethyuan** [comment]
有提示语的那个小窗口应该不会自己消失吧，有没有看到红色的失败文字？可以在右键菜单里打开console看看有没有抛错。

**Comment by yanyang1025** [comment]
> 有提示语的那个小窗口应该不会自己消失吧，有没有看到红色的失败文字？可以在右键菜单里打开console看看有没有抛错。

感谢您的回复！现在是“获取数据……”大概3-4分钟会出现红色的失败文字。有可能是因为数据太多了吗？其他配置都是按照 instruction来的，也重新退出登录了微信读书，换过port和密文什么的。

之前我在obsidian上一直是用这个插件：zhaohongxuan/obsidian-weread-plugin: Obsidian Weread Plugin is a plugin to sync Weread(微信读书) hightlights and annotations into your Obsidian Vault. https://github.com/zhaohongxuan/obsidian-weread-plugin

最近换到 logseq 上来希望这个也能work。非常感谢！

**Comment by sethyuan** [comment]
不太确定，等失败之后右击红色文字进console截个图看看具体的错误信息是什么吧。

**Comment by yanyang1025** [comment]
> 不太确定，等失败之后右击红色文字进console截个图看看具体的错误信息是什么吧。

谢谢您，不知道具体的错误信息这个算吗？不知道里面说的“请先登录”是怎么回事呀（绝对登录了）？有没有可能是chrome安装的其他插件冲突了呢？

<img width="1039" alt="image" src="https://github.com/sethyuan/logseq-plugin-weread-sync/assets/32084920/92c34141-143d-438d-a1ad-4b9f32e5a474">

**Comment by yanyang1025** [comment]
> > 不太确定，等失败之后右击红色文字进console截个图看看具体的错误信息是什么吧。
> 
> 谢谢您，不知道具体的错误信息这个算吗？不知道里面说的“请先登录”是怎么回事呀（绝对登录了）？有没有可能是chrome安装的其他插件冲突了呢？
> 
> <img alt="image" width="1039" src="https://private-user-images.githubusercontent.com/32084920/300293772-92c34141-143d-438d-a1ad-4b9f32e5a474.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0Nzk1OTgsIm5iZiI6MTcwNjQ3OTI5OCwicGF0aCI6Ii8zMjA4NDkyMC8zMDAyOTM3NzItOTJjMzQxNDEtMTQzZC00MzhkLWExYWQtNGI5ZjMyZTVhNDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDIyMDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYmEyNTA5MzIxM2I2NjA4ZmYzNjAxZTM4Yzc1MDQzNWI2NGZkYTUxYzM4YzE4ZTgyMDU3NTlmZTJiMjgwZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k12fnFyKTaFx_pR9_ESCyaB9iTpO2bY8MFsXb_D-bkw">

const SITE_URLS = ["https://i.weread.qq.com", "https://weread.qq.com"]
const BATCH = 100

async function main(...args) {
  const [tab] = await chrome.tabs.query({
    active: true,
    currentWindow: true,
  })
  if (tab?.url && SITE_URLS.some((url) => tab.url.startsWith(url))) {
    await sync(tab)
  } else {
    await openWeReadTab()
  }
}

async function sync(tab) {
  const msgEl = document.getElementsByClassName("msg")[0]
  msgEl.classList.remove("success", "failure")

  try {
    const vid = (await chrome.cookies.get({ name: "wr_vid", url: tab.url }))
      .value
    const {
      [`${vid}_booksSyncKey`]: booksSyncKey,
      [`${vid}_bookmarksSyncKey`]: bookmarksSyncKey,
      [`${vid}_reviewsSyncKey`]: reviewsSyncKey,
      noSyncBookList,
    } = await chrome.storage.sync.get({
      [`${vid}_booksSyncKey`]: "",
      [`${vid}_bookmarksSyncKey`]: "",
      [`${vid}_reviewsSyncKey`]: "",
      noSyncBookList: "",
    })

    msgEl.textContent = "获取数据……"
    const res = await chrome.tabs.sendMessage(tab.id, {
      op: "getData",
      args: [
        vid,
        booksSyncKey,
        bookmarksSyncKey,
        reviewsSyncKey,
        noSyncBookList,
      ],
    })
    if (res?.code !== 200) {
      return errorMsg(msgEl, res.code, res.err)
    }

    msgEl.textContent = "与Logseq同步中……"
    const syncDataRes = await syncData(res.data)
    if (syncDataRes?.code !== 200) {
      return errorMsg(msgEl, syncDataRes.code)
    }

    await chrome.storage.sync.set({
      [`${vid}_booksSyncKey`]: res.data.books.syncKey,
      [`${vid}_bookmarksSyncKey`]: res.data.bookmarks.syncKey,
      [`${vid}_reviewsSyncKey`]: res.data.reviews.syncKey,
    })
  } catch (err) {
    errorMsg(msgEl, 400, err)
  }

  msgEl.textContent = "完成"
  msgEl.classList.add("success")
}

async function syncData(data) {
  const { apiUrl, token } = await chrome.storage.local.get({
    apiUrl: "http://localhost:12315",
    token: "",
  })
  let res
  res = await syncRemoved(data, apiUrl, token)
  if (res.code !== 200) return res
  res = await syncBooks(data, apiUrl, token)
  if (res.code !== 200) return res
  res = await syncBookmarks(data, apiUrl, token)
  if (res.code !== 200) return res
  res = await syncReviews(data, apiUrl, token)
  if (res.code !== 200) return res
  return res
}

async function syncRemoved(data, apiUrl, token) {
  data = {
    books: {
      removed: data.books.removed,
      updated: [],
    },
    bookmarks: {
      removed: data.bookmarks.removed,
      updated: [],
    },
    reviews: {
      removed: data.reviews.removed,
      updated: [],
    },
  }
  return await syncCall(data, apiUrl, token)
}

async function syncBooks(data, apiUrl, token) {
  const batches = splitArray(data.books.updated, BATCH)
  let res = { code: 200 }
  for (const batch of batches) {
    data = {
      books: {
        removed: [],
        updated: batch,
      },
      bookmarks: {
        removed: [],
        updated: [],
      },
      reviews: {
        removed: [],
        updated: [],
      },
    }
    res = await syncCall(data, apiUrl, token)
    if (res.code !== 200) return res
  }
  return res
}

async function syncBookmarks(data, apiUrl, token) {
  const batches = splitArray(data.bookmarks.updated, BATCH)
  let res = { code: 200 }
  for (const batch of batches) {
    data = {
      books: {
        removed: [],
        updated: [],
      },
      bookmarks: {
        removed: [],
        updated: batch,
      },
      reviews: {
        removed: [],
        updated: [],
      },
    }
    res = await syncCall(data, apiUrl, token)
    if (res.code !== 200) return res
  }
  return res
}

async function syncReviews(data, apiUrl, token) {
  const batches = splitArray(data.reviews.updated, BATCH)
  let res = { code: 200 }
  for (const batch of batches) {
    data = {
      books: {
        removed: [],
        updated: [],
      },
      bookmarks: {
        removed: [],
        updated: [],
      },
      reviews: {
        removed: [],
        updated: batch,
      },
    }
    res = await syncCall(data, apiUrl, token)
    if (res.code !== 200) return res
  }
  return res
}

async function syncCall(data, apiUrl, token) {
  const res = await fetch(`${apiUrl}/api`, {
    method: "POST",
    credentials: "omit",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      method: "logseq.App.invokeExternalPluginCmd",
      args: ["logseq-weread-sync", "models", "receiveSyncData", [data]],
    }),
  })
  if (!res.ok) return { code: res.status }
  const ok = await res.json()
  if (!ok) return { code: 400 }
  return { code: 200 }
}

function splitArray(arr, n) {
  const ret = new Array(Math.ceil(arr.length / n))
  for (let i = 0; i < ret.length; i++) {
    ret[i] = arr.slice(i * n, (i + 1) * n)
  }
  return ret
}

function errorMsg(msgEl, code, err) {
  msgEl.classList.add("failure")
  switch (code) {
    case 401:
      msgEl.textContent = "请先登录微信读书"
      break
    default:
      msgEl.textContent = "同步失败"
      console.error(code, err)
      break
  }
}

async function openWeReadTab() {
  await chrome.tabs.create({ url: "https://weread.qq.com" })
}

document.addEventListener("DOMContentLoaded", main)

**Comment by sethyuan** [comment]
需要再看下微信读书中的console，里面应该有错误信息。还是在出现红色错误文字之后看哈。把错误信息展开截图，不用贴文字。

**Comment by me115** [comment]
> 需要再看下微信读书中的console，里面应该有错误信息。还是在出现红色错误文字之后看哈。把错误信息展开截图，不用贴文字。

你好，@sethyuan,  我遇到了同样的问题，也是第一次同步，报错，以下是报错信息；weixin读书的console里没有任何信息：
<img width="972" alt="image" src="https://github.com/sethyuan/logseq-plugin-weread-sync/assets/7226606/61996fdb-935a-4ced-acc3-9741cedfc2dd">
