### ISSUE TITLE
想法采用quote, 原文变成正常字体

### ISSUE THREAD

**Issue by carmen41511** [sethyuan/logseq-plugin-weread-sync#18]
![image](https://github.com/sethyuan/logseq-plugin-weread-sync/assets/53323902/0dbfcdb0-e4cc-4248-a5d8-5b196fd46e90)

可不可以把想法放到红色的quote的框框里面 （markdown的右箭头 `>`），原文变成正常字体。就是把它们两个的顺序调换？
也许可以用一个flag来控制原文还是想法才去采用 quote

我看了看应该是[这行代码](https://github.com/sethyuan/logseq-plugin-weread-sync/blob/master/src/libs/reviews.js#L71)

**Comment by sethyuan** [comment]
我可以加个插件配置，根据配置来决定是否反转。另外你找到的代码是对的，你有兴趣的话也可以提个PR给我。 😀

**Comment by sethyuan** [comment]
已经实现了，请尝试新版本。
