### ISSUE TITLE
[功能要求] 筛选图书同步

### ISSUE THREAD

**Issue by NNGTHB** [sethyuan/logseq-plugin-weread-sync#2]
请问能增加一个指定图书同步这样的功能吗？因为书架上有些书不想同步到logseq，想挑选特定的书同步。

**Comment by sethyuan** [comment]
可以加，但是我在想如何做比较好。也许通过微信读书的书单功能来实现，也就是用户建一个不公开的书单，里面放不想被同步的书籍。

**Comment by NNGTHB** [comment]
> 可以加，但是我在想如何做比较好。也许通过微信读书的书单功能来实现，也就是用户建一个不公开的书单，里面放不想被同步的书籍。

ok感觉这样也可以

**Comment by sethyuan** [comment]
@NNGTHB 这个功能已添加。注意两边的插件都要更新到最新版本。在插件的选项框里可以设置书单名了。
![image](https://user-images.githubusercontent.com/3410293/221512117-f313d0be-6b8d-4dd3-9d13-03b258858cd5.png)

**Comment by NNGTHB** [comment]
> @NNGTHB 这个功能已添加。注意两边的插件都要更新到最新版本。在插件的选项框里可以设置书单名了。 ![image](https://user-images.githubusercontent.com/3410293/221512117-f313d0be-6b8d-4dd3-9d13-03b258858cd5.png)

OK
