### ISSUE TITLE
输入隐藏元数据的代码，没有效果，元数据已然在。

### ISSUE THREAD

**Issue by chenghuangjulv** [sethyuan/logseq-plugin-weread-sync#23]
在config.edn中输入隐藏元数据的代码，没有效果，元数据已然在。另外如何取消出版日期，它会同步到日志里，太麻烦了
![image](https://github.com/user-attachments/assets/0ffed023-63f9-4abc-871c-42a2a5999cc8)
![image](https://github.com/user-attachments/assets/63c38ac2-7ee5-44e8-838c-e99cc82c849c)

**Comment by sethyuan** [comment]
看起来配置是对的，重启下Logseq试试看呢，再不行可能就是高版本的Logseq有什么改动了？这个配置是Logseq提供的，与插件本身没有关系。
另外关于出版日期，准确地说它不是同步到了日记里，而是反向链接到了日记的那一天，这个是Logseq作为双链笔记的特色。

**Comment by HotlinkQiu** [comment]
看起来，几个“：”是中文的字符？我试了一下都成功隐藏了。
