### ISSUE TITLE
一直提醒未登录

### ISSUE THREAD

**Issue by Arvid-pku** [sethyuan/logseq-plugin-weread-sync#3]
感谢制作了这个插件，会很方便我这样的微信读书+logseq的用户
但在第一次尝试的时候，插件一直提示未登录是为什么呀。
![image](https://user-images.githubusercontent.com/53811705/228419699-b55dd9ee-ff80-45b9-b852-3bda0dbe8c5b.png)

**Comment by sethyuan** [comment]
建议检查下是否是因为没有给插件足够的权限导致的。
![image](https://user-images.githubusercontent.com/3410293/228446547-5c4f8f5c-35e4-4917-93e2-f0a843418254.png)

另外首次同步取决于数据量可能同步时间会较长，请耐心等待。

**Comment by Arvid-pku** [comment]
已经开启了这些权限
![image](https://user-images.githubusercontent.com/53811705/228453427-ea3457d8-a76a-498e-b685-b22c03c5d8f7.png)
也尝试过重启、切换代理之类的

**Comment by sethyuan** [comment]
从错误上是没有拿到登录信息导致的，但是很奇怪为什么会拿不到。要不你网站上退出再重新登录一下试试呢。

**Comment by Arvid-pku** [comment]
重新登录仍然不行。
但我发现关闭logseq的API后，点击chrome插件显示同步成功。（这时候logseq内确实没有被同步）
但当打开API之后，就显示需要登录了

**Comment by sethyuan** [comment]
你检查下chrome插件的配置和Logseq的API Server的配置对的上不？
![image](https://user-images.githubusercontent.com/3410293/228458755-ad8d362a-0985-4e34-81f5-62f11f71c80c.png)

**Comment by Arvid-pku** [comment]
啊可以了！非常感谢！确实是token打错了😭 感谢感谢
![image](https://user-images.githubusercontent.com/53811705/228460229-5e82df6c-0860-4919-b3dc-b10403d72519.png)

**Comment by Arvid-pku** [comment]
PS 请问曾经读完但移出书架的可以同步嘛

**Comment by sethyuan** [comment]
不要移出书架，移出会被同步为删除。你可以建一个分组，不想看到的就放进那个分组里。

**Comment by Arvid-pku** [comment]
您好，清除之后有效果了。但开始一直显示同步失败。跟#1问题差不多。
logseq的console中显示：
![image](https://user-images.githubusercontent.com/53811705/228507648-2175ac5d-c36c-4645-9160-4aa315befd1c.png)
