### ISSUE TITLE
第一次全量同步失败

### ISSUE THREAD

**Issue by gongxianshengjiadexiaohuihui** [sethyuan/logseq-plugin-weread-sync#5]
![image](https://user-images.githubusercontent.com/39046975/229389683-5ee75710-549f-4d10-8069-e878d0356b63.png)
第一次全量同步失败，后面不同，没有笔记部分
![image](https://user-images.githubusercontent.com/39046975/229389726-f6e8e55a-f085-4c58-a7d7-4a51e16a737e.png)

**Comment by sethyuan** [comment]
请确保两边用的都是最新版的插件，如果是麻烦看下两边的错误日志，发上来看看是什么错。

**Comment by gongxianshengjiadexiaohuihui** [comment]
![image](https://user-images.githubusercontent.com/39046975/229397846-e60299d9-9f8a-4268-a2fb-f7f19c206177.png)
![image](https://user-images.githubusercontent.com/39046975/229397889-dbe4a751-64da-4a56-8175-7767c34df491.png)
两边都是最新的。
都显示的200，日志在那里看，console和network没有报错，只是谷歌插件会显示同步失败

**Comment by sethyuan** [comment]
看你的描述应该是Logseq端会有错误日志才对。你可以在Logseq里打开console，（ctrl+shift+i 或者 cmd+shift+i），在chrome插件设置里将增量key清除，再重新同步看看。
![image](https://user-images.githubusercontent.com/3410293/229404686-3d9d7677-90a3-4c41-a74e-abfc6568fedf.png)

**Comment by gongxianshengjiadexiaohuihui** [comment]
![image](https://user-images.githubusercontent.com/39046975/229414756-00ff15f3-9e55-4bbb-b83c-1e8a27144d01.png)

**Comment by sethyuan** [comment]
感觉是你之前有一个页面的名字和微信读书里的书名一样，但是这个页面是空白的，没有属性块导致的。我再改下代码兼容一下，遇到这种情况就自动插入一个页面属性块。

**Comment by sethyuan** [comment]
@gongxianshengjiadexiaohuihui 我更新了一版Logseq端插件，你清理掉增量key再试试呢。

**Comment by gongxianshengjiadexiaohuihui** [comment]
谢谢大佬，可以了，您做的这款插件太棒了，太符合我的需求了，如果，笔记能够导航到原文，就更爽了

**Comment by sethyuan** [comment]
我也一直想实现这个功能，之前研究过，但无法得知web版微信读书是怎么生成的url，做不到跳转。这块我一直关注下吧。
