### ISSUE TITLE
每次拉取新的数据，书籍页面的属性被覆盖

### ISSUE THREAD

**Issue by MountainEthics** [sethyuan/logseq-plugin-weread-sync#6]
![image](https://user-images.githubusercontent.com/127084213/233334558-f1364751-6bb0-47d4-81be-61e7fa96e7d9.png)
本身我已经自定义了书籍的属性，但是在使用这个插件的过程中会被覆盖掉。

是否可以保留用户自定义的页面属性，在使用插件更新内容，页面仅仅更新插件默认的属性。
或者允许用户选择不更新页面属性。

**Comment by sethyuan** [comment]
目前插件的行为就是这样的，用户自定义的属性是会保留的。你用的Logseq是什么版本？建议升级到最新版本，有几个版本的Logseq在属性处理这块有bug，导致属性没有同步，我怀疑你可能是这种情况。
