### ISSUE TITLE
同步过来的书籍名称过长以及未做笔记的书仅仅在书架也会同步

### ISSUE THREAD

**Issue by MountainEthics** [sethyuan/logseq-plugin-weread-sync#8]
大佬，
同步的书籍名称过长，似乎把副标题也同步成了页面名字，见图片
![image](https://user-images.githubusercontent.com/127084213/235204469-11450126-8ea0-4cd9-852e-d5e7b5a16da8.png)
zhej这出现一个问题，这么长的名字，官方云同步到移动端失败，一直卡在不断同步的界面。

这个刚导入的书籍，并未做笔记，也会先同步过来，这是默认的吗？

**Comment by sethyuan** [comment]
是的，书架上的书都会同步，相对的，从书架上移除也会在同步时移除，除非书籍页面已经被引用了。

关于书名，你可以尝试修改书籍页面的名字，同步是靠书籍id识别的，所以改名字应该没影响。
