### ISSUE TITLE
配置好后点击插件提示 需要登录微信读书，实际已经登录了

### ISSUE THREAD

**Issue by Jungley8** [sethyuan/logseq-plugin-weread-sync#9]
![image](https://user-images.githubusercontent.com/20501682/236657059-7fe4c37a-7711-4866-a4e4-3bd91d018c8b.png)

其他人有出现吗？

**Comment by sethyuan** [comment]
检查下地址和token是否配置正确了。

**Comment by FengZiGG** [comment]
我也遇到了差不多的。
我配置好了，也登录了，点击插件，显示在获取数据，等了一会之后同步失败，再次点击还是失败，会说我没登录，但实际我已经登录了的，然后我点击退出登录，试着重新登录，扫码，手机上会提示登录失败，重新扫码。需要浏览器清除缓存，才能再次登录，同步依旧是失败的。

**Comment by sethyuan** [comment]
检查下地址和token是否配置正确了，API Server有没有开启。

**Comment by baresibest** [comment]
配置完成后，再次点击，很快就出现了完成按钮，但是logseq端并没有任何同步信息。

**Comment by sethyuan** [comment]
@baresibest 不会显示任何信息的，你看书和笔记导入进来没有嘛。
